services:
  db:
    image: postgres:16.0-alpine3.18
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - pgdata:/var/lib/postgresql
    ports:
      - '5432:5432'

  pgadmin:
    image: dpage/pgadmin4:7.7
    environment:
      PGADMIN_DEFAULT_EMAIL: test@example.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - '9001:80'

  app:
    image: tasks:latest
    environment:
      - DATABASE_URL=postgresql://postgres:password@host.docker.internal:5432/tasks?schema=public
    ports:
      - '8080:3000'
volumes:
  pgdata:
